# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-22.04
  apt_packages:
    - make
  tools:
    python: "3.9"
  jobs:
    pre_build:
      - ls -alh
      - cd docs && make api

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
formats: all

python:
  install:
  - requirements: docs/requirements.txt
