name: "timeeval"
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - pip=20
  - scikit-learn=0.23.*
  - matplotlib=3.3.*
  - numpy
  - pandas
  - pip:
      - tqdm==4.54.*
      - dask[distributed]==2021.1.*
      - asyncssh==2.5.*
